"""Build LibraryRecipes.lua: the profession recipe index the Library reads.

Blizzard's DB2 tables (SkillLineAbility, SpellReagents, SpellEffect, ItemEffect)
come from wago.tools as CSV. Forever has no build there, so the latest Classic
Era build stands in; recipes Forever adds are learned in game when a profession
window opens (Library.lua LB.Learn).

Each recipe spell becomes one row:
    [spellID] = { skillLine, makesItemID, makesCount, taughtByItemID, reagentID, count, ... }

Usage:
    python tools/make_library.py [build]
"""
import csv
import io
import json
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "LibraryRecipes.lua"
API = "https://wago.tools"

PROFESSIONS = {
    164: "Blacksmithing", 165: "Leatherworking", 171: "Alchemy", 185: "Cooking",
    186: "Mining", 197: "Tailoring", 202: "Engineering", 333: "Enchanting",
    129: "First Aid",
}
CREATE_ITEM, LEARN_SPELL = 24, 36


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "ImprovedController-tools"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.read().decode("utf-8")


def table(name, build):
    text = fetch(f"{API}/db2/{name}/csv?build={build}")
    return list(csv.DictReader(io.StringIO(text)))


def latest_build():
    builds = json.loads(fetch(f"{API}/api/builds"))
    return builds["wow_classic_era"][0]["version"]


def main():
    build = sys.argv[1] if len(sys.argv) > 1 else latest_build()
    print(f"build {build}")

    skill = {}
    for row in table("SkillLineAbility", build):
        line = int(row["SkillLine"])
        if line in PROFESSIONS:
            skill[int(row["Spell"])] = line

    reagents = {}
    for row in table("SpellReagents", build):
        spell = int(row["SpellID"])
        if spell not in skill:
            continue
        pairs = []
        for i in range(8):
            item, count = int(row[f"Reagent_{i}"]), int(row[f"ReagentCount_{i}"])
            if item > 0 and count > 0:
                pairs += [item, count]
        reagents[spell] = pairs

    makes, learns = {}, defaultdict(list)
    for row in table("SpellEffect", build):
        effect, spell = int(row["Effect"]), int(row["SpellID"])
        if effect == CREATE_ITEM and spell in skill and int(row["EffectItemType"]) > 0:
            count = int(row["EffectBasePoints"]) + max(int(row["EffectDieSides"]), 1)
            makes[spell] = (int(row["EffectItemType"]), max(count, 1))
        elif effect == LEARN_SPELL and int(row["EffectTriggerSpell"]) > 0:
            learns[spell].append(int(row["EffectTriggerSpell"]))

    taught = {}
    for row in table("ItemEffect", build):
        item, spell = int(row["ParentItemID"]), int(row["SpellID"])
        for recipe in learns.get(spell, ()):
            if recipe in skill:
                taught.setdefault(recipe, item)

    rows = []
    for spell in sorted(skill):
        if spell not in reagents and spell not in makes:
            continue
        make, count = makes.get(spell, (0, 0))
        fields = [skill[spell], make, count, taught.get(spell, 0)] + reagents.get(spell, [])
        rows.append(f"[{spell}]={{{','.join(map(str, fields))}}},")

    names = ", ".join(f"[{k}] = \"{v}\"" for k, v in sorted(PROFESSIONS.items()))
    OUT.write_text(
        "-- GENERATED by tools/make_library.py from Blizzard DB2 tables (wago.tools).\n"
        "-- Do not edit by hand. Row: { skillLine, makesItemID, makesCount, taughtByItemID,\n"
        "-- reagentID, count, reagentID, count, ... }\n"
        "local _, IC = ...\n"
        f"IC.LibraryRecipes = {{ build = \"{build}\",\n"
        f"skills = {{ {names} }},\n"
        "recipes = {\n" + "\n".join(rows) + "\n} }\n",
        encoding="utf-8",
    )
    print(f"{len(rows)} recipes, {len(taught)} taught by items -> {OUT.name}")


if __name__ == "__main__":
    main()
